---
stages:
  - test
  - docker

cache:
  key: "$CI_PROJECT_PATH-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
  paths:
    - vendor/apt
    - vendor/ruby
  untracked: true

before_script:
  - mkdir -p vendor/apt
  - apt-get update -qq
  - apt-get install -o dir::cache::archives="vendor/apt" -qq -y --no-install-recommends --no-install-suggests gnupg2 libgpgme11-dev libsqlite3-dev eatmydata
  - eatmydata gem install bundler --no-ri --no-rdoc
  - eatmydata bundle install --jobs $(nproc) --path vendor
  - rm /dev/random && ln -s /dev/urandom /dev/random
  - SCHLEUDER_ENV=test SCHLEUDER_CONFIG=spec/schleuder.yml eatmydata bundle exec rake db:create db:schema:load

ruby:2.1:
  image: ruby:2.1
  script:
    - eatmydata bundle exec rspec
ruby:2.2:
  image: ruby:2.2
  script:
    - eatmydata bundle exec rspec
ruby:2.3:
  image: ruby:2.3
  script:
    - eatmydata bundle exec rspec
ruby:2.4:
  image: ruby:2.4
  script:
    - eatmydata bundle exec rspec
ruby:2.5:
  image: ruby:2.5
  script:
    - eatmydata bundle exec rspec

bundler:audit:
  image: ruby:2.4
  script:
    - gem install bundler-audit
    - bundle install --jobs $(nproc) --path vendor
    - bundle-audit update
    - bundle-audit check
  allow_failure: true

build_docker_image:
  stage: docker
  # Only build packages for https://0xacab.org/schleuder/schleuder, not
  # for forks
  only:
    - master@schleuder/schleuder
    - tags@schleuder/schleuder
  tags:
    - docker-in-docker
  before_script:
    - docker info
  image: docker:latest
  services:
    - docker:dind
  variables:
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - docker build -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG
