before_script:
  - gem install bundler
  - bundle install
  - apt-get -qq update
  - apt-get install -y gnupg2 libgpgme11-dev libsqlite3-dev haveged
  - SCHLEUDER_ENV=test SCHLEUDER_CONFIG=spec/schleuder.yml bundle exec rake db:create db:schema:load
ruby:2.1:
  image: ruby:2.1
  script:
    - bundle exec rspec
ruby:2.2:
  image: ruby:2.2
  script:
    - bundle exec rspec
ruby:2.3:
  image: ruby:2.3
  script:
    - bundle exec rspec
ruby:2.4:
  image: ruby:2.4
  script:
    - bundle exec rspec

