---
image: ruby:latest

check_travis_builds:
  script:
    - apt-get update -qq
    - apt-get install --no-install-recommends --no-install-suggests -qq -y python-requests
    - ./utils/ci/check_travis_builds.py
bundler:audit:
  script:
    - gem install bundler-audit
    - gem install bundler --no-ri --no-rdoc
    - bundle install
    - bundle-audit update
    - bundle-audit check
  allow_failure: true

